version: '0'

services:

  app1:
    build: .
    container_name: app1
    ports:
      - "3000:3000"
    environment:
      - MESSAGE=Bienvenidos a Lab02

  app2:
    build: .
    container_name: app2
    ports:
      - "3001:3000"
    environment:
      - MESSAGE=Bienvenidos a Lab02